spring.application.name=GestLivres

# Configuration de la base de donn?es PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Bibliotheque
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (ORM) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Affiche les requ?tes SQL dans la console
spring.jpa.show-sql=true


# Sp?cifie le mode de chargement des transactions
spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/

server.port = 8005